platform :ios, "8.1"

target "BikeRental" do

use_frameworks!
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage'
pod 'Masonry'
pod 'IQKeyboardManager'
pod 'WZLBadge'
pod 'DateTools'
pod 'SDCycleScrollView','~> 1.64'
pod 'SVProgressHUD'
pod 'FDFullscreenPopGesture', '1.1'
pod 'UITableView+FDTemplateLayoutCell'
pod 'TZImagePickerController'
pod 'DZNEmptyDataSet'
pod 'BEMCheckBox'
pod 'Bugly'
pod 'TOWebViewController'
pod 'AMap3DMap'
pod 'AMapLocation'
pod 'AMapSearch'
pod 'QMUIKit'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/QQ'
pod 'pop'
pod 'WebViewJavascriptBridge'
pod 'LBXScan', '~> 2.2'
pod 'JDFTooltips'
pod 'JPush'
end
